### ISSUE TITLE
Support storyboard

### ISSUE THREAD

**Issue by tony-hoang999** [touchlane/CampcotCollectionView#8] opened 2019-10-30 21:02 UTC
Hello,
I tried to use the CampcotCollectionView in storyboard but couldn't. I ran into this error
```
required public init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
}
```
Could you please help fix that. Thank you!

**Comment by AlexYanski** [comment] 2020-02-14 08:50
@tony-hoang999 Hello! Thanks for your feedback! Now the issue is resolved in 0.0.7 release.
Check out new readme about how to setup storyboard based CampcotCollectionView.

**Closed as completed by AlexYanski** 2020-02-14 08:50 UTC
